spring:
  profiles:
    # 默认激活 dev 环境
    active: dev
  mail:
    host: smtp.qq.com # 邮件服务器的地址，这里使用QQ邮件
    username: 1535769515@qq.com  # 替换成你的QQ邮箱
    password: fljmvzxglsmugcab  # 替换成你的QQ邮箱授权码
    default-encoding: utf-8
    protocol: smtps
    port: 465
    
jwt:
  # 签发人
  issuer: weblog
  # 秘钥（使用base64编码的字符串）
  secret: d2VibG9nLXNlY3JldC1rZXktYmFzZTY0LWVuY29kZWQ=
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer